# Generated by Django 4.1 on 2023-01-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
